Fix duplicate names in .ui files

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -6,7 +6,7 @@
 #
 # it is MUCH faster, smaller and does what I want. :-)
 #
-# If you have openssl or the Berkeley db installed in 
+# If you have openssl or the Berkeley db installed in
 # an unusual directory like /home/me/install/ssl
 # just give it as argument to ./configure
 # it then searches for headers in /home/me/install/ssl/include
@@ -14,7 +14,7 @@
 #
 # if you have a very unusual setup or you are cross-compiling
 # you can edit "Local.mak" to fit your needs and to reflect your setup
-# 
+#
 # The Makefiles should support parallel builds.
 #
 #######################################################
@@ -37,7 +37,7 @@ LRELEASE=lrelease
 err() {
   echo
   echo ERROR: $1
-  echo 
+  echo
   err_occ=Y
 }
 
@@ -48,7 +48,7 @@ add_include() {
       return 0
     fi
   done
- 
+
   CF="${CF} -I$1"
 }
 
@@ -57,7 +57,7 @@ add_lib() {
     SLIBS="$SLIBS -l$2"
   else
     LIBS="$LIBS -l$2"
-  fi  
+  fi
   for _libs in -L/usr/lib ${LDIRS}; do
     if test "-L$1" = "${_libs}"; then
       return 0
@@ -97,13 +97,13 @@ search_lib() {
   done
   return 1
 }
- 
+
 echo -e "\n\nConfiguring XCA `cat VERSION`\n----------------------------"
 
 ######################### QT
 subdirs="/qt /qt4"
 search_includes Qt/qobject.h || err "The QT Library headerfiles were not found. Set QTDIR appropriately."
-search_lib QtGui qt qt-mt || err "The QT library was not found. Try installing qt-dev" 
+search_lib QtGui qt qt-mt || err "The QT library was not found. Try installing qt-dev"
 search_lib c_r || true
 
 ###################### OpenSSL
@@ -122,7 +122,7 @@ main(){
   printf("\nThe Versions of the used libraries are:\n\t%s\n\tQT: %s\n",
 	 OPENSSL_VERSION_TEXT, QT_VERSION_STR );
   if (QT_VERSION < 0x040001) {
-	printf("You need Qt 4 or greater\n");
+	printf("You need Qt 4 or higher\n");
 	return 1;
   }
   return 0;
@@ -185,7 +185,7 @@ for dirs in /bin /usr/bin /usr/local/bin /sw/bin; do
     if ${dirs}/${make} -v 2>/dev/null | grep GNU; then
       mak=${dirs}/${make}
     fi
-  done  
+  done
 done
 
 echo
