fix compiling issues for 0.5.1

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -32,7 +32,6 @@ LIBS=-lstdc++
 LDIRS=
 MOC=moc
 UIC=uic
-LRELEASE=lrelease
 
 err() {
   echo
@@ -53,11 +52,7 @@ add_include() {
 }
 
 add_lib() {
-  if test "$3" = "a"; then
-    SLIBS="$SLIBS -l$2"
-  else
-    LIBS="$LIBS -l$2"
-  fi  
+  LIBS="$LIBS -l$2"
   for _libs in -L/usr/lib ${LDIRS}; do
     if test "-L$1" = "${_libs}"; then
       return 0
@@ -73,7 +68,6 @@ search_includes() {
     for dbn in "" ${subdirs}; do
       if test -r ${dir}/include${dbn}/$1; then
           add_include ${dir}/include${dbn}
-	  test -z "${dbn}" || add_include ${dir}/include
           echo Found:  $1 at ${dir}/include${dbn}
           return 0
       fi
@@ -86,9 +80,9 @@ search_includes() {
 search_lib() {
   for dir in ${DIRS};  do
     for dbn in $@; do
-      for suffix in so dylib obj a; do
+      for suffix in so dylib obj; do
         if test -r ${dir}/lib/lib${dbn}.${suffix}; then
-          add_lib ${dir}/lib ${dbn} ${suffix};
+          add_lib ${dir}/lib ${dbn};
 	  echo Found: lib${dbn}.${suffix} at ${dir}/lib
           return 0
 	fi
@@ -98,10 +92,9 @@ search_lib() {
   return 1
 }
  
-echo -e "\n\nConfiguring XCA `cat VERSION`\n----------------------------"
 
 ######################## DB
-subdirs="/db /db4.1 /db4 /db3"
+subdirs="/db /db4.2 /db4.1 /db4 /db3"
 search_includes db_cxx.h || err "The Berkeley DB header files were not found"
 search_lib db_cxx db4_cxx db_cxx-4 db3_cxx db_cxx-3 || err "The Berkeley DB library was not found. Try installing db-dev" 
 ## The fun of NPTL... (Thx Enrico Scholz)
@@ -113,9 +106,9 @@ else
 fi
 
 ######################### QT
-subdirs="/qt /Qt /qt4 /qt3 /qt2"
+subdirs="/qt /qt3 /qt2"
 search_includes qobject.h || err "The QT Library headerfiles were not found. Set QTDIR appropriately."
-search_lib QtGui qt qt-mt || err "The QT library was not found. Try installing qt-dev" 
+search_lib qt qt-mt || err "The QT library was not found. Try installing qt-dev" 
 search_lib c_r || true
 # look if it compiles...
 if g++ $LIBS $LDIRS $CF $CFLAGS conftest.c -o conftest &>conftest.log; then
@@ -159,15 +152,11 @@ if test -x $QTDIR/bin/uic; then
   UIC="$QTDIR/bin/uic"
 fi
 
-if test -x $QTDIR/bin/lrelease; then
-  LRELEASE="$QTDIR/bin/lrelease"
-fi
-
 echo
 echo "LDFLAGS   :${LIBS}${LDIRS}"
 echo "PREFIX    :${prefix:=/usr/local}"
 echo "CPPFLAGS  :${CF}"
-echo "CFLAGS    :${CFLAGS:=-Wall -g -ggdb}"
+echo "CFLAGS    :${CFLAGS:=-Wall}"
 echo
 
 cat >Local.mak <<EOF
@@ -175,16 +164,10 @@ CPPFLAGS=$CF
 CFLAGS=${CFLAGS}
 
 LDFLAGS=$LDIRS
-
-# List of all libs to be compiled statically
-SLIBS=$SLIBS
-
-# list of dynamic libraries
 LIBS=$LIBS
 
 MOC=$MOC
 UIC=$UIC
-LRELEASE=$LRELEASE
 
 CC=${CC:=gcc}
 LD=${LD:=ld}
