We are going to  0.9.2. Use pkgconfig in configure if possible

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -163,22 +163,33 @@ check_frameworks() {
   return 0
 }
 
-######################### QT
-if test -z "$DARWIN"; then
-  subdirs="/qt /qt4"
-  search_includes QtCore/QObject || err "The QT Library headerfiles were not found. Set QTDIR appropriately."
-  search_lib QtCore4 QtCore || err "The QT Core library was not found."
-  search_lib QtGui4 QtGui || err "The QT Gui library was not found."
-  search_lib ltdl || err "Libtool ltdl not found."
-  search_lib c_r || true
+if test "$#" = "0" && test -z "$DARWIN" && \
+   pkg-config QtGui openssl --libs >/dev/null;
+then
+  CF="`pkg-config QtGui openssl --cflags`"
+  LIBS="`pkg-config QtGui openssl --libs` -lltdl"
 else
-  check_frameworks QtGui QtCore || err "QT Framework not found, needed on Mac OSX, please install QT"
+  by_hand=true
 fi
 
-###################### OpenSSL
-subdirs=""
-search_includes openssl/opensslv.h || err "The OpenSSL library headerfiles were not found."
-search_lib crypto || err "The OpenSSL library was not found."
+if test "$by_hand" = "true"; then
+  ######################### QT
+  if test -z "$DARWIN"; then
+    subdirs="/qt /qt4"
+    search_includes QtCore/QObject || err "The QT Library headerfiles were not found. Set QTDIR appropriately."
+    search_lib QtCore4 QtCore || err "The QT Core library was not found."
+    search_lib QtGui4 QtGui || err "The QT Gui library was not found."
+    search_lib ltdl || err "Libtool ltdl not found."
+    search_lib c_r || true
+  else
+    check_frameworks QtGui QtCore || err "QT Framework not found, needed on Mac OSX, please install QT"
+  fi
+
+  ###################### OpenSSL
+  subdirs=""
+  search_includes openssl/opensslv.h || err "The OpenSSL library headerfiles were not found."
+  search_lib crypto || err "The OpenSSL library was not found."
+fi
 
 cat << EOF
 
